import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";

export const metadata: Metadata = {
    title: "Cleaning Service",
    description: "Generated by M. Tsvetanov",
    themeColor: "#ffffff", // keeps browser UI light
    other: { "color-scheme": "light" }, // tells UA: only light scheme
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body>
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
